/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaleIndexRouteImport } from './routes/$locale/index'
import { Route as LocaleSlugIndexRouteImport } from './routes/$locale/$slug.index'
import { Route as LocaleSlugChildRouteImport } from './routes/$locale/$slug.$child'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleIndexRoute = LocaleIndexRouteImport.update({
  id: '/$locale/',
  path: '/$locale/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSlugIndexRoute = LocaleSlugIndexRouteImport.update({
  id: '/$locale/$slug/',
  path: '/$locale/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaleSlugChildRoute = LocaleSlugChildRouteImport.update({
  id: '/$locale/$slug/$child',
  path: '/$locale/$slug/$child',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$slug/$child': typeof LocaleSlugChildRoute
  '/$locale/$slug/': typeof LocaleSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$locale': typeof LocaleIndexRoute
  '/$locale/$slug/$child': typeof LocaleSlugChildRoute
  '/$locale/$slug': typeof LocaleSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$locale/': typeof LocaleIndexRoute
  '/$locale/$slug/$child': typeof LocaleSlugChildRoute
  '/$locale/$slug/': typeof LocaleSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/$locale/' | '/$locale/$slug/$child' | '/$locale/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/$locale' | '/$locale/$slug/$child' | '/$locale/$slug'
  id:
    '__root__' | '/' | '/$locale/' | '/$locale/$slug/$child' | '/$locale/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaleIndexRoute: typeof LocaleIndexRoute
  LocaleSlugChildRoute: typeof LocaleSlugChildRoute
  LocaleSlugIndexRoute: typeof LocaleSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/': {
      id: '/$locale/'
      path: '/$locale'
      fullPath: '/$locale/'
      preLoaderRoute: typeof LocaleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$slug/': {
      id: '/$locale/$slug/'
      path: '/$locale/$slug'
      fullPath: '/$locale/$slug/'
      preLoaderRoute: typeof LocaleSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$locale/$slug/$child': {
      id: '/$locale/$slug/$child'
      path: '/$locale/$slug/$child'
      fullPath: '/$locale/$slug/$child'
      preLoaderRoute: typeof LocaleSlugChildRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaleIndexRoute: LocaleIndexRoute,
  LocaleSlugChildRoute: LocaleSlugChildRoute,
  LocaleSlugIndexRoute: LocaleSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
